name: "Godot Mono Build"
description: "Build a Godot mono project for multiple platforms greatly inspired by yeslayla/build-godot-action -> https://github.com/yeslayla/build-godot-action/tree/master"
author: lilian1024
inputs:
  name:
    description: 'Name of the exported binary'
    required: true
  preset:
    description: 'Name of the preset in `export_presets.cfg` to use'
    required: true
  debugMode:
    description: 'Whether or not to use `--export-debug`'
    default: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.name }}
    - ${{ inputs.preset }}
    - ${{ inputs.debugMode }}